// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-xoD58dwAMz_bL3xSnKhquezKIjWW2Y',
    appId: '1:480066974770:web:cada516ca3a99b1922f82b',
    messagingSenderId: '480066974770',
    projectId: 'terraria-progression',
    authDomain: 'terraria-progression.firebaseapp.com',
    storageBucket: 'terraria-progression.firebasestorage.app',
    measurementId: 'G-XE4QNPYXBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtGzE20ZTInLcK7JldN_c9g9pW29XJT5Y',
    appId: '1:480066974770:android:1a36f4e90db188ca22f82b',
    messagingSenderId: '480066974770',
    projectId: 'terraria-progression',
    storageBucket: 'terraria-progression.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2hJEtTnc5JvsmToKq6_fzyApf2eA3IyA',
    appId: '1:480066974770:ios:c0931e8254f0bf8c22f82b',
    messagingSenderId: '480066974770',
    projectId: 'terraria-progression',
    storageBucket: 'terraria-progression.firebasestorage.app',
    iosBundleId: 'com.example.terrariaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2hJEtTnc5JvsmToKq6_fzyApf2eA3IyA',
    appId: '1:480066974770:ios:c0931e8254f0bf8c22f82b',
    messagingSenderId: '480066974770',
    projectId: 'terraria-progression',
    storageBucket: 'terraria-progression.firebasestorage.app',
    iosBundleId: 'com.example.terrariaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe-xoD58dwAMz_bL3xSnKhquezKIjWW2Y',
    appId: '1:480066974770:web:336fbe5a04e2be6022f82b',
    messagingSenderId: '480066974770',
    projectId: 'terraria-progression',
    authDomain: 'terraria-progression.firebaseapp.com',
    storageBucket: 'terraria-progression.firebasestorage.app',
    measurementId: 'G-XDSYYBZNSF',
  );
}